### ISSUE TITLE
product show > product section checklist

### ISSUE THREAD

**Issue by lhsgm** [lhsgm/tomorrow-house#1]
## Checklist

- Tab + Tabpanel 구조
  - [ ] `role` 을 사용해서 유기적 연결관계 구축
- 공통 컴포넌트
   - [ ] Tabpanel header 영역
     - [ ]  텍스트 only
     - [ ]  텍스트 + 뱃지 + 아이콘링크
     - [ ]  택스트 + 뱃지 + 텍스트링크
     - [ ]  텍스트 + 뱃지 + 아이콘버튼(드랍다운 메뉴 only mobile)
  - [ ] Tabpanel 내 `table`
